### PR TITLE
Update database-connection.js

### PR DESCRIPTION
**Pull request by vitaly-t**
better use of the `ColumnSet` :wink:

### CODE REVIEW

**Comment by vitaly-t** [comment]
See type [Column](http://vitaly-t.github.io/pg-promise/helpers.Column.html) :wink:

**Comment by SergioV85** [comment]
Can I use such approach in opposite case? When I do a SELECT, but want as output an Object with another properties name, then column name?

**Comment by vitaly-t** [comment]
If you are talking about remapping INNER JOIN, see this: https://stackoverflow.com/questions/39805736/get-join-table-as-array-of-results-with-postgresql-nodejs

If you want to camelize columns, see this: http://vitaly-t.github.io/pg-promise/global.html#event:receive

**Comment by vitaly-t** [comment]
@SergioV85 probably what you need is method [map] or [each], depending on the re-mapping logic :wink:

[map]:http://vitaly-t.github.io/pg-promise/Database.html#map
[each]:http://vitaly-t.github.io/pg-promise/Database.html#each

**Pull request merged**
